---
- name: Install Docker
  ansible.builtin.apt:
    name: 
      - docker.io
      - python3-docker
    state: present
    update_cache: yes

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Pull LightHouse Docker image
  community.docker.docker_image:
    name: lighthouse/lighthouse  # Замените на выбранный вами образ
    tag: latest
    source: pull

- name: Run LightHouse container
  community.docker.docker_container:
    name: lighthouse
    image: lighthouse/lighthouse:latest  # Замените на выбранный вами образ
    state: started
    restart_policy: always
    published_ports:
      - "8080:80"
